class CustomComputeException(Exception):
    """Exception triggered when a custom check fails to return a dataframe"""

    pass
